const cuisines = [
  { id: 1, name: "Món Việt" },
  { id: 12, name: "Món Miền Nam" },
  { id: 2, name: "Món Bắc" },
  { id: 7, name: "Món Miền Trung" },
  { id: 29, name: "Tây Nguyên" },
  { id: 36, name: "Món Á" },
  { id: 22, name: "Món Hàn" },
  { id: 21, name: "Món Nhật" },
  { id: 4, name: "Món Trung Hoa" },
  { id: 17, name: "Món Thái" },
  { id: 30, name: "Singapore" },
  { id: 31, name: "Malaysia" },
  { id: 38, name: "Campuchia" },
  { id: 42, name: "Philippines" },
  { id: 37, name: "Indonesia" },
  { id: 16, name: "Món Ấn Độ" },
  { id: 51, name: "Đài Loan" },
  { id: 53, name: "Iran" },
  { id: 34, name: "Món Âu" },
  { id: 19, name: "Pháp" },
  { id: 18, name: "Ý" },
  { id: 20, name: "Đức" },
  { id: 35, name: "Tây Ban Nha" },
  { id: 25, name: "Thụy sĩ" },
  { id: 52, name: "Bánh Pizza" },
  { id: 24, name: "Châu Mỹ" },
  { id: 33, name: "Mỹ" },
  { id: 32, name: "Brazil" },
  { id: 39, name: "Mexico" },
  { id: 40, name: "Canada" },
  { id: 46, name: "Argentina" },
  { id: 50, name: "Quốc tế" },
  { id: 28, name: "Đông Âu" },
  { id: 43, name: "Thổ Nhĩ Kỳ" },
  { id: 44, name: "Tiệp (Séc)" },
  { id: 47, name: "Úc" },
  { id: 26, name: "Bắc Âu" },
  { id: 27, name: "Trung Đông" },
  { id: 41, name: "Ả Rập" },
  { id: 23, name: "Châu Phi" },
  { id: 54, name: "Đặc biệt" },
  { id: 55, name: "Đặc sản vùng" },
];

export default cuisines;
